[package]
name = "jk"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
config = { version = "0.15.4", features = ["toml"] }
git2 = "0.19.0"
gpgme = "0.11.0"
inquire = "0.7.5"
once_cell = "1.20.2"
regex = "1.11.1"
reqwest = { version = "0.12.10", features = ["json"] }
serde = { version = "1.0.216", features = ["derive"] }
tokio = { version = "1.42.0", features = ["full"] }
